### ISSUE TITLE
Color scheme discussion

### ISSUE THREAD

**Issue by jGaboardi** [pysal/logo#16]
After the [02/2020 meeting](https://hackmd.io/NXcgMbMNTVep8Zw6rmouBg?both#logofavicon-colors-decision-James) we are nearly settled on logo colors.

* @knaaptime suggested something more darker hues of pinks/yellow opposed to the purple seen [here in cell 7](https://github.com/pysal/logo/blob/master/logo_palette.ipynb).
* @pedrovma mentioned a preference for yellow.

This issue can serve as a final decision/discussion to hammer this out. Anyone please make correction/edits as needed.

also related to #11 and #12

**Comment by jGaboardi** [comment]
Here's some shading examples on both light and dark backgrounds with labels so it's easier for us to tell which color/shade is which:

**Light background — `color` into black**

<img width="851" alt="light_background" src="https://user-images.githubusercontent.com/8590583/74067803-08e91000-49c8-11ea-9d13-efcec1520478.png">




---------------------
**Dark background — `color` into white**


<img width="851" alt="dark_background" src="https://user-images.githubusercontent.com/8590583/74067816-0f778780-49c8-11ea-9faa-4b96a995aaa1.png">

**Comment by jGaboardi** [comment]
Also, these may look nice blended into blues, etc. I will put up some more swatches later.

**Comment by knaaptime** [comment]
> @knaaptime suggested something more darker hues of pinks/yellow opposed to the purple seen here in cell 7 .

to be clear, I *love* the purple on the left in cell 7, but I loathe the magenta on the right. My take is that we're too heavy on the red end of the spectrum (two reds, an orange and a brown) and my preference would be to replace the brown with something like a yellow and maybe one of the reds with something like turquoise or aqua or something nearer to that end of the spectrum

**Comment by jGaboardi** [comment]
> to be clear, I love the purple on the left in cell 7, but I loathe the magenta on the right. My take is that we're too heavy on the red end of the spectrum (two reds, an orange and a brown) and my preference would be to replace the brown with something like a yellow and maybe one of the reds with something like turquoise or aqua or something nearer to that end of the spectrum.

+1!

I will include some options for you in a new swatch!

**Comment by jGaboardi** [comment]
@knaaptime, let me know what you think about these shades. I tried to (1) get a nice aqua and matte yellow; (2) get a shade a red that was between the two from before; and (3) keep the grape wine.

Also looking for input in layout.

![pysal_logo](https://user-images.githubusercontent.com/8590583/74071810-ed373700-49d2-11ea-9060-b39a104e91ac.png)

**Comment by knaaptime** [comment]
that's not bad! is there some way i can test rotating colors in, like trying something like #3CAEA3 for the new blue?

**Comment by knaaptime** [comment]
another option might be to bootstrap from something like https://coolors.co/2e4057-66a182-edae49-d1495b-00798c

which is kinda nice because then get e.g. complimentary shading

**Comment by jGaboardi** [comment]
I am having some serious issues getting lualatex/tikz to play nice with hex formatted colors, even when trying to [define a color though `HTML`](https://en.wikibooks.org/wiki/LaTeX/Colors#Color_Models). However, I did have some success with defined colors through the `rbg` and `RBG` schemes. I am going give it a whirl in the morning, as it requires some refactoring of the code, but then we would be able to define our own colors a bit more easily, [like so](http://latexcolor.com).

Also, I am planning on merging in the 3 PRs (for my own sanity) tomorrow, unless there are any objections.

**Comment by jGaboardi** [comment]
@knaaptime I've been swamped with my actual job and haven't had time to finish this up, but should be able to get around to submitting a PR with a new & more flexible structure in the next few days.

**Comment by knaaptime** [comment]
👍 no rush, i'm also buried :)

**Comment by knaaptime** [comment]
also, i'd be curious to see this one swapped for the light blue

![image](https://user-images.githubusercontent.com/4213368/74360569-29bfb580-4d7a-11ea-8ce9-572f4e298eea.png)

**Comment by jGaboardi** [comment]
The new structure I am working on will allow for easily passing in (a) [pre-defined colors based on their name](http://latexcolor.com); or (b) the `RGB` formula, `#3CAEA3`-->`RGB(60, 174, 163)`. This will make it much less cumbersome to test out and decide on new colors.

**Comment by jGaboardi** [comment]
As a side note... I just realized that adding back ticks to an HTML color code displays the actual color in GitHub Markdown! 

#3CAEF3 --> `#3CAEF3`

**Comment by knaaptime** [comment]
ha, nice!

**Comment by jGaboardi** [comment]
#19

**Comment by knaaptime** [comment]
![image](https://user-images.githubusercontent.com/4213368/74638742-5b8d9f00-5121-11ea-83d9-a976b7d79f33.png)

**Comment by jGaboardi** [comment]
I like this a lot.

**Comment by jGaboardi** [comment]
What do we think about replacing the current colors in [`canon2020` (cell 12)](https://github.com/pysal/logo/blob/master/PySAL_logo_creation.ipynb) with Eli's [proposed color scheme (cell 20)](https://github.com/pysal/logo/blob/master/PySAL_logo_creation.ipynb)? This will become the new standard, default PySAL logo. I'm down with it.

@knaaptime @weikang9009 @sjsrey

**Comment by jGaboardi** [comment]
Finalizing this discussion in #24
