### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by sjsrey** [pysal/logo#20]
`python create_pysal_logo.py` results in:

```
(/usr/share/texlive/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tik
zlibrarytopaths.code.tex)))
! Bad number (18).
l.921     \ifeof18 
                 \else 3\fi
? 
```

**Comment by jGaboardi** [comment]
I am working on `logo` right now. I'll take a look at this once I get the fresh version pushed up.

**Comment by sjsrey** [comment]
Version info: `This is LuaTeX, Version 1.0.4 (TeX Live 2017/Debian) `

**Comment by jGaboardi** [comment]
I am running `This is LuaTeX, Version 1.10.0 (TeX Live 2019)`. I'll make a note of this in the requirements.

**Comment by sjsrey** [comment]
Using ` pdflatex pysal_text_log.tex ` works so it is an issue with luatex.

**Comment by sjsrey** [comment]
https://tex.stackexchange.com/questions/386349/lualatex-complains-when-using-convert-in-standalone

**Comment by sjsrey** [comment]
Updating [luatex](https://www.tug.org/texlive/acquire-netinstall.html) to 1.10 fixes the issue.
