### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/logo#31]
Change default branch from `master` to `main`. For more info see pysal/libpysal#353.

**Comment by jGaboardi** [comment]
I don't have admin privileges for the repo. @knaaptime Do you? If so, can you change the default in *Settings/Branch* to `main`?

**Comment by knaaptime** [comment]
na, me neither

**Comment by jGaboardi** [comment]
> na, me neither

@sjsrey would you be able to grant @knaaptime and I admin privileges for this repo?
