### ISSUE TITLE
reorganize repo?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/logo#7]
Depending on what the team thinks about #6, I propose we move the old stuff in the repo into a `historic/` directory and move the contents of `pysal_2-1_logo/` in the main directory (and remove `pysal_2-1_logo/`.

**Comment by jGaboardi** [comment]
Being addressed in #10

**Comment by knaaptime** [comment]
i'd go even further and say just blast the old stuff instead of moving it to `historic`. We can always dig through the git history if we need it

**Comment by jGaboardi** [comment]
Done.
